api:
  build: ./server
  command: npm start
  ports:
    - "80:8080"
  links:
    - mongodb
  environment:
    - NODE_ENV=development
    - MONGODB_ADDRESS=mongodb
  restart: always
mqtt-client:
  build: ./mqtt/Client
  command: npm start
  links:
    - api
  environment:
    - NODE_ENV=development
    - API_ADDRESS=api
    - MQTT_ADDRESS=52.67.204.136
  restart: always
mongodb:
  image: mongo
  restart: always
