api:
  build: ./server
  command: npm start
  ports:
    - "8080:8080"
  links:
    - mongodb
    - mongodb:mongodb.cloud66.local
  environment:
    - NODE_ENV=development
    - MONGODB_ADDRESS=mongodb
mqtt-client:
  build: ./mqtt/Client
  command: npm start
  links:
    - api
    - mqtt-broker
  environment:
    - NODE_ENV=development
    - API_ADDRESS=api
    - MQTT_ADDRESS=mqtt-broker
mqtt-broker:
  image: projetosigtrac/mosquitto
  ports:
    - "1883:1883"
mongodb:
  image: mongo
